language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: HfWRMBLoScEneoMj2bQqwkAqkqm8Wx/UIg3RJFWM41gHdRY7TZLNTWspQfMQcRv/8euoC+md8VDsUR2v5yWBwq0JCGrOJc4G+TKzUbI+7qw6O8xOYQ9HaR1ff34xU+3kgwFdcyfscY+7fWbIz/URP1j66j3LOmxv5sm3R9tNUiyziUPWhPiWC2jRUAE3QnEOmRRkr8B/rth2rkenXQIaBHDr1xnoJhZ9HwZim8NMbT+Ns1JSgYOOQw7KWdjhF3Ei5MiFu4Q+JMQBO8EOaTl7rur/uJJxCNMk5MBw9tNs+D+phC4SXLgwqo2BBCNG4o8DsGcFDgkyEQQjf+Kt9M4DxZ76O6BzAfiIpqV16a768JW+AbLaZUAlDd3uqwn07jdCLYst7e+5tOW66ejPadxOqTSW+g0gScHpPKLaU1HKRBOgOtlKhJB0yE4s/6z72hN2/6nqG3Ry5+uWMrjrWoCPSMpIwwx/DV3OOB+yhCU5uUoSJQkuSxkE3Ho7TLhyJPMFEXXnpM5dOxj07qrIKP4N1HB+kEvwGYxMztm8juY10RlyCgzkspQQolV1hWbEExB0829hy/e9FKRdE/u1sTyo5vKhqns6X+i4Nf/25yxewV5/+AeoztaH8FObULa2tqqiu7McxItP2PcYeZLIx7bPWuKe3UszokTczjNwt36mP6g=
  app: shielded-everglades-00105