language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: EtiKws5zsHlvp0CS9j47Nxod3Ta2LEhimt7dspCrrwDipGmjACkjpjDpGmJ/9qFC9MqqfIeLSUoL/G7Dc6H4iEWRnVTaos2fnl2IW5iZgM2fAqMI6o22Y3KeOgcwy/R13YFQRFVo6H6eE+/Zvai2fPdckONnyWxRteKHV78Sexsm9q4B5izBG1bo03TN6yNbhgvqyPuUdOr8epCu/KwPYPcTwbuDPGhIcFQScTpxUkPIHkPaDUKkKeiBVPpey3XiI0HXUwVNcJzwDpI2OOo8Fc6k7kLNHCwt3XV3p48Cu/icLAb3hzs5liQoqQJX/43TKWj0rJObNwO+JIcODTVX92S4ojRfJNV0RBDFYFGmHbkzVg1Vx0DSoNNBPOBmCv5Hb+eP/6gXPp+W+2b4XRB2SVTxzW4ZtNRwgIcM/ICdIoo058hmDGUSk9x5Z1FQUR2qNgE81a+V9mhA1e72bnCv6KBnfDmZx0pQYOZQSAaiDPkiaSo1Z9wER5nDMTha76A8twzbVBfYLrTTnA+/ugwJT7Ssa0DGwhzx+6VxfJj9QfQnDGexKTo9iBdfLgwKGZiRkZ7ccKnmHCyhIGDIZ4sCeoJiKHwviviG0lagIDhhQciCfazRU2RNWZnE3TcUoyMD/cq9V2dqreWIydBOsueuDsUaA1zPWf+TapCqZkmUP5I=
  app: shielded-everglades-00105